---
title: "Distribuições Estatísticas"
author: "Jose Storopoli"
output: html_notebook
---

# Distribuições Estatísticas

## Discretas

### Uniforme Discreta

### Binomial

### Poisson

### Geométrica

### Hipergeométrica

## Contínuas

### Uniforme Contínua

### Normal / Gaussiana

```{r}
x <- seq(-4, 4, length = 100)

dps <- c(0.5, 1, 2, 5)
colors <- c("red", "blue", "darkgreen", "gold")
labels <- c("dp=0.5", "dp=1", "dp=2", "dp=5")

plot(NA, xlab="valor de x",
  ylab="Densidade",
  main="Comparativo de Distribuições Normais",
  xlim = c(-4, 4),
  ylim = c(0, 1))

for (i in 1:4){
  lines(x, dnorm(x, mean = 0, sd = dps[i]), lwd=2, col=colors[i])
}

legend("topright", inset=.05, title="Desvio Padrões",
  labels, lwd=2, lty=c(1, 1, 1, 1, 2), col=colors)
```

### Lognormal

### Exponencial

### Distribuição t de Student

```{r}
x <- seq(-4, 4, length = 100)

degfs <- c(1, 3, 8, 30)
colors <- c("red", "blue", "darkgreen", "gold")
labels <- c("df=1", "df=3", "df=8", "df=30")

plot(NA, xlab="valor de x",
  ylab="Densidade",
  main="Comparativo de Distribuições t de Student",
  xlim = c(-4, 4),
  ylim = c(0, 0.5))

for (i in 1:4){
  lines(x, dt(x,df = dps[i]), lwd=2, col=colors[i])
}

legend("topright", inset=.05, title="Graus de Liberdade",
  labels, lwd=2, lty=c(1, 1, 1, 1, 2), col=colors)
```

