name: rmarkdown

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:
jobs:

  # 1st job
  render_site:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Setup tinytex
        uses: r-lib/actions/setup-tinytex@v1

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: 2.11.4

      - name: Install Packages
        run: Rscript .binder/install.R

      - name: Render Site
        run: |
          Rscript -e 'rmarkdown::clean_site(preview = FALSE)'
          Rscript -e 'rmarkdown::render_site()'

  # 2nd job
  push_changes:
    runs-on: macos-latest
    needs: [render_site]
    steps:
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - name: Commit files
        if: steps.extract_branch.outputs.branch == 'master' || steps.extract_branch.outputs.branch == 'main'
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
          git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
          NO_PAGER=1 git --no-pager diff HEAD^

      - name: Push changes
        if: steps.extract_branch.outputs.branch == 'master' || steps.extract_branch.outputs.branch == 'main'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
